root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./main.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]

[log]
  level = "debug"

[watcher]
  extensions = ["go", "tmpl", "html"]
  ignore_dirs = ["tmp", "vendor", ".git"]